#!/usr/bin/env python2.7
"""
    svgmap - a simple toolset that helps creating interactive thematic maps
    Copyright (C) 2011  Gregor Aisch

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

"""
	This is the command line interface for svgmap.
"""

import sys, os.path, getopt

from lib.svgmap import SVGMap, SVGMapOptions

def usage():
	print '\nUsage: '+os.path.basename(sys.argv[0])+' command'
	print 'Possible commands are:\n'
	
	print '   country      renders country boundary'
	print '   countries    ""'
	print '   regions      renders all admin-level 1 regions of a country'
	print '   region       renders a single admin-level 1 region of a country'
	print '   world        renders world map'
	print '   layer        adds a new layer from a shapefile'
	print '   bbox         '
	print

	
def main():
	global command, options
	
	parse_args()
	
	svgmap = SVGMap(options)
	
	if command == "world":
		svgmap.render_world_map(outfile=options.outfile)
		
	if command == "bbox":
		svgmap.render_world_map(outfile=options.outfile)
		
	elif command in ("country", "regions"):
		iso3 = options.target_countries[0]
		out = options.outfile
		regions = command == "regions"
		
		if options.add_context:
			svgmap.render_country_and_context(iso3, outfile=out, regions=regions)	
		else:
			svgmap.render_country(iso3, outfile=out, regions=regions)
		
	elif command == "region":
		iso3 = options.target_countries[0]
		out = options.outfile
		
		if options.add_context:
			svgmap.render_country_and_context(iso3, outfile=out, regions=True, focusRegion=options.focus_region)	
		else:
			svgmap.render_country(iso3, outfile=out, regions=True, focusRegion=options.focus_region)
		
	elif command == "layer":
		svg_src = options.svg_src
		shp_src = options.shapefile_src
		data_col = options.layer_data_column
		svgmap.add_shapefile_layer(svg_src, shp_src, data_column = data_col, outfile=options.outfile)
		
	elif command == "countries":
		svgmap.render_countries(options.target_countries, outfile=options.outfile)


def list_projections():
	import lib.proj
	
	print 'available projections are:'
	for pj in lib.proj.projections:
		print '  - %s' % pj
	print



def parse_args():
	
	global command, options
	
	import math
	
	options = SVGMapOptions()
	
	if len(sys.argv) < 2:
		usage()
		sys.exit(2)
	
	command = sys.argv[1]
	
	if command not in ('world','country','regions','layer','region','countries','bbox'):
		usage()
		sys.exit(2)
	
	# parse options
	# global options
	opt_str = "o:w:h:r:p:q:sfvg:l"
	long_opt = ['output=', 'width=', 'height=', 'ratio=', 'padding=', 'quality=', 'sea', 'force-overwrite', 'context-quality=', 'verbose', 'proj=','list-projections','graticule=','round-coordinates','lon0=','lat0=','lat1=','lat2=','dist=','up=', 'tilt=', 'cut-lakes', 'flip']

	if command == "world":
		opt_str += ''
		cmd_args = sys.argv[2:]
		long_opt += ['filter=','filter-col=']
		
	if command == "bbox":
		if len(sys.argv) < 3:
			print '\nError: you must define a lonlat bounding box'
			print '       e.g. -180,-90,180,90'
			print
			sys.exit(2)
		options.llbbox = map(float, sys.argv[2].split(','))
		long_opt += ['filter=','filter-col=']
		cmd_args = sys.argv[3:]
		
	if command == "countries":
		if len(sys.argv) < 3:
			print '\nError: you must define the countries to be rendered'
			print
			sys.exit(2)
		long_opt += []
		opt_str += 'g'
		options.target_countries = sys.argv[2].split(',')
		cmd_args = sys.argv[3:]
		
	
	if command in ('regions', 'country'):
		if len(sys.argv) < 3:
			print '\nError: you must define the country to be rendered, e.g.\n\n   '+os.path.basename(sys.argv[0])+' '+command+' USA'
			print '   '+os.path.basename(sys.argv[0])+' '+command+' USA,DEU,CHN\n   '+os.path.basename(sys.argv[0])+' '+command+' all'
			print
			sys.exit(2)
		else:
			options.target_countries = sys.argv[2].split(',')
			long_opt += ['context']
			opt_str += "c"	
			cmd_args = sys.argv[3:]
	
	if command in ('regions', 'region'):
		long_opt += ['join-regions']
		opt_str += 'j'
		
	if command == "layer":
		if len(sys.argv) < 4:
			print "\nError: you must provide a svg-map and a shapefile\n\n"+os.path.basename(sys.argv[0])+' '+command+' SVGMAP.svg SHAPEFILE'
			sys.exit(2)
		else:
			long_opt += ['layer-id=', 'crop-at-layer=', 'data-col=']
			long_opt += ['filter=','filter-col=']
			options.svg_src = sys.argv[2]
			options.shapefile_src = sys.argv[3]
			cmd_args = sys.argv[4:]
			
	if command == "region":
		if len(sys.argv) < 5:
			print "\nError: wrong number of arguments\n\n"+os.path.basename(sys.argv[0])+' '+command+' ISO3 REC-COLUMN REC-COLUMN-VALUE'
			sys.exit(2)
		else:
			options.target_countries = [sys.argv[2]]
			options.focus_region = (int(sys.argv[3]), sys.argv[4])
			cmd_args = sys.argv[5:]
			long_opt += ['context']
			opt_str += "c"
	
	try:
		opts, args = getopt.getopt(cmd_args, opt_str, long_opt)
		
		for o, a in opts:
			if o in ('-w', '--width'):
				options.out_width = int(a)
			elif o in ('-h', '--height'):
				options.out_height = int(a)
			elif o in ('-r', '--ratio'):
				options.out_ratio = float(a)
				options.force_ratio = True
			elif o in ('-v', '--verbose'):
				options.verbose = True
			elif o in ('-o', '--output'):
				options.outfile = a
			elif o in ('-c', '--context'):
				options.add_context = True
			elif o in ('--padding', '-p'):
				options.out_padding_perc = float(a)/100
			elif o in ('-q', '--quality'):
				q = max(0, min(100, float(a)))/100.0
				options.simplification = 100 - math.pow(q,.25)*100
			elif o in ('--context-quality'):
				q = max(0, min(100, float(a)))/100.0
				options.context_simplification = 100 - math.pow(q,.25)*100
			elif o in ('-s', '--sea'):
				options.sea_layer = True
			elif o in ('-f', '--force-overwrite'):
				options.force_overwrite = True
			elif o == '--crop-at-layer':
				options.crop_at_layer = a
			elif o == '--layer-id':
				options.layer_id = a
			elif o in ('--join-regions', '-j'):
				options.join_regions = True
			elif o in ('-g', '--graticule'):
				options.graticule = True
				options.grat_step = int(a)
			elif o == '--round-coordinates':
				options.round_coordinates = True
			elif o == "--data-col":
				options.layer_data_column = a.split(',')
			elif o in ('--cut-lakes', '-l'):
				options.cut_lakes = True
			
			# projection options
			elif o == '--list-projections':
				list_projections()
				sys.exit(2)
			elif o in ('--proj'):
				import lib.proj
				if a in lib.proj.projections:
					options.projection = lib.proj.projections[a]
				else:
					print 'projection "%s" not found' % a
					list_projections()
					sys.exit(2)
			elif o == '--lon0':
				options.proj_opts['lon0'] = float(a)
				options.force_lon0 = True
			elif o == '--lat0':
				options.proj_opts['lat0'] = float(a)
				options.force_lat0 = True
			elif o == '--lat1':
				options.proj_opts['lat1'] = float(a)
				options.force_lat1 = True
			elif o == '--lat2':
				options.proj_opts['lat2'] = float(a)
			elif o == '--dist':
				options.proj_opts['dist'] = float(a)
			elif o == '--up':
				options.proj_opts['up'] = float(a)
			elif o == '--tilt':
				options.proj_opts['tilt'] = float(a)
			elif o == '--flip':
				options.proj_opts['flip'] = 1
			elif o == '--filter':
				m = a[0]
				codes = a[1:].upper().split(',')
				options.filter_mode = m
				options.filter_codes = codes
			elif o == '--filter-col':
				options.filter_column = a
			

		options.applyDefaults(command)
		
	except getopt.GetoptError, err:
		print str(err)
		usage()
		sys.exit(2)
	


if __name__ == "__main__":
    main()
